version: 2
project_name: castsponsorskip
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions --date={{ .CommitDate }}
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - grpcnotrace
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    mod_timestamp: "{{.CommitTimestamp}}"
    ignore:
      - goos: windows
        goarch: arm
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - manpages/*
      - completions/*
      - systemd/{{ .ProjectName }}.service
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: '\(deps\):'
    - title: Others
      order: 998
dockers:
  - &dockers
    image_templates:
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-armv6
    goarch: arm
    goarm: 6
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - <<: *dockers
    image_templates:
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/ap-andersson/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/ap-andersson/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
