version: 2
project_name: castsponsorskip
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions --date={{ .CommitDate }}
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - grpcnotrace
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    mod_timestamp: "{{.CommitTimestamp}}"
    ignore:
      - goos: windows
        goarch: arm
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - manpages/*
      - completions/*
      - systemd/{{ .ProjectName }}.service
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: '\(deps\):'
    - title: Others
      order: 998
dockers_v2:
  - images:
      - ghcr.io/ap-andersson/{{ .ProjectName }}
    dockerfile: goreleaser.Dockerfile
    platforms:
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
      - "{{ if not .IsSnapshot }}{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}{{ .Major }}.{{ .Minor }}{{ end }}"
