FROM alpine:3.18
WORKDIR /app

RUN apk add --no-cache tzdata

COPY sponsorblockcast-go .

ARG USERNAME=sponsorblockcast-go
ARG UID=1000
ARG GID=$UID
RUN addgroup -g "$GID" "$USERNAME" \
    && adduser -S -u "$UID" -G "$USERNAME" "$USERNAME"
USER $UID

CMD ["./sponsorblockcast-go"]
